#############################################################################
# Makefile for building: project
# Generated by qmake (2.01a) (Qt 4.8.3) on: Mon Jun 17 10:09:13 2013
# Project:  project.pro
# Template: subdirs
# Command: /usr/lib/qt4/bin/qmake -o Makefile project.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/lib/qt4/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-src \
		sub-themes \
		sub-translations \
		sub-demos \
		sub-tests

src/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /home/ramoncin/socam/svn/socam/trunk/UX/meegotouch-systemui/src/src.pro -o $(MAKEFILE)
sub-src-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /home/ramoncin/socam/svn/socam/trunk/UX/meegotouch-systemui/src/src.pro -o $(MAKEFILE)
sub-src: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE)
sub-src-make_default: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_first: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) first
sub-src-all: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) all
sub-src-clean: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-distclean: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-install_subtargets: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) install
sub-src-uninstall_subtargets: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) uninstall
themes/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) themes/ || $(MKDIR) themes/ 
	cd themes/ && $(QMAKE) /home/ramoncin/socam/svn/socam/trunk/UX/meegotouch-systemui/themes/themes.pro -o $(MAKEFILE)
sub-themes-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) themes/ || $(MKDIR) themes/ 
	cd themes/ && $(QMAKE) /home/ramoncin/socam/svn/socam/trunk/UX/meegotouch-systemui/themes/themes.pro -o $(MAKEFILE)
sub-themes: themes/$(MAKEFILE) FORCE
	cd themes/ && $(MAKE) -f $(MAKEFILE)
sub-themes-make_default: themes/$(MAKEFILE) FORCE
	cd themes/ && $(MAKE) -f $(MAKEFILE) 
sub-themes-make_first: themes/$(MAKEFILE) FORCE
	cd themes/ && $(MAKE) -f $(MAKEFILE) first
sub-themes-all: themes/$(MAKEFILE) FORCE
	cd themes/ && $(MAKE) -f $(MAKEFILE) all
sub-themes-clean: themes/$(MAKEFILE) FORCE
	cd themes/ && $(MAKE) -f $(MAKEFILE) clean
sub-themes-distclean: themes/$(MAKEFILE) FORCE
	cd themes/ && $(MAKE) -f $(MAKEFILE) distclean
sub-themes-install_subtargets: themes/$(MAKEFILE) FORCE
	cd themes/ && $(MAKE) -f $(MAKEFILE) install
sub-themes-uninstall_subtargets: themes/$(MAKEFILE) FORCE
	cd themes/ && $(MAKE) -f $(MAKEFILE) uninstall
translations/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) translations/ || $(MKDIR) translations/ 
	cd translations/ && $(QMAKE) /home/ramoncin/socam/svn/socam/trunk/UX/meegotouch-systemui/translations/translations.pro -o $(MAKEFILE)
sub-translations-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) translations/ || $(MKDIR) translations/ 
	cd translations/ && $(QMAKE) /home/ramoncin/socam/svn/socam/trunk/UX/meegotouch-systemui/translations/translations.pro -o $(MAKEFILE)
sub-translations: translations/$(MAKEFILE) FORCE
	cd translations/ && $(MAKE) -f $(MAKEFILE)
sub-translations-make_default: translations/$(MAKEFILE) FORCE
	cd translations/ && $(MAKE) -f $(MAKEFILE) 
sub-translations-make_first: translations/$(MAKEFILE) FORCE
	cd translations/ && $(MAKE) -f $(MAKEFILE) first
sub-translations-all: translations/$(MAKEFILE) FORCE
	cd translations/ && $(MAKE) -f $(MAKEFILE) all
sub-translations-clean: translations/$(MAKEFILE) FORCE
	cd translations/ && $(MAKE) -f $(MAKEFILE) clean
sub-translations-distclean: translations/$(MAKEFILE) FORCE
	cd translations/ && $(MAKE) -f $(MAKEFILE) distclean
sub-translations-install_subtargets: translations/$(MAKEFILE) FORCE
	cd translations/ && $(MAKE) -f $(MAKEFILE) install
sub-translations-uninstall_subtargets: translations/$(MAKEFILE) FORCE
	cd translations/ && $(MAKE) -f $(MAKEFILE) uninstall
demos/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) demos/ || $(MKDIR) demos/ 
	cd demos/ && $(QMAKE) /home/ramoncin/socam/svn/socam/trunk/UX/meegotouch-systemui/demos/demos.pro -o $(MAKEFILE)
sub-demos-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) demos/ || $(MKDIR) demos/ 
	cd demos/ && $(QMAKE) /home/ramoncin/socam/svn/socam/trunk/UX/meegotouch-systemui/demos/demos.pro -o $(MAKEFILE)
sub-demos: demos/$(MAKEFILE) FORCE
	cd demos/ && $(MAKE) -f $(MAKEFILE)
sub-demos-make_default: demos/$(MAKEFILE) FORCE
	cd demos/ && $(MAKE) -f $(MAKEFILE) 
sub-demos-make_first: demos/$(MAKEFILE) FORCE
	cd demos/ && $(MAKE) -f $(MAKEFILE) first
sub-demos-all: demos/$(MAKEFILE) FORCE
	cd demos/ && $(MAKE) -f $(MAKEFILE) all
sub-demos-clean: demos/$(MAKEFILE) FORCE
	cd demos/ && $(MAKE) -f $(MAKEFILE) clean
sub-demos-distclean: demos/$(MAKEFILE) FORCE
	cd demos/ && $(MAKE) -f $(MAKEFILE) distclean
sub-demos-install_subtargets: demos/$(MAKEFILE) FORCE
	cd demos/ && $(MAKE) -f $(MAKEFILE) install
sub-demos-uninstall_subtargets: demos/$(MAKEFILE) FORCE
	cd demos/ && $(MAKE) -f $(MAKEFILE) uninstall
tests/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) tests/ || $(MKDIR) tests/ 
	cd tests/ && $(QMAKE) /home/ramoncin/socam/svn/socam/trunk/UX/meegotouch-systemui/tests/tests.pro -o $(MAKEFILE)
sub-tests-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) tests/ || $(MKDIR) tests/ 
	cd tests/ && $(QMAKE) /home/ramoncin/socam/svn/socam/trunk/UX/meegotouch-systemui/tests/tests.pro -o $(MAKEFILE)
sub-tests: tests/$(MAKEFILE) FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE)
sub-tests-make_default: tests/$(MAKEFILE) FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) 
sub-tests-make_first: tests/$(MAKEFILE) FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) first
sub-tests-all: tests/$(MAKEFILE) FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) all
sub-tests-clean: tests/$(MAKEFILE) FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) clean
sub-tests-distclean: tests/$(MAKEFILE) FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) distclean
sub-tests-install_subtargets: tests/$(MAKEFILE) FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) install
sub-tests-uninstall_subtargets: tests/$(MAKEFILE) FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: project.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		shared.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile project.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
shared.pri:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile project.pro

qmake_all: sub-src-qmake_all sub-themes-qmake_all sub-translations-qmake_all sub-demos-qmake_all sub-tests-qmake_all FORCE

make_default: sub-src-make_default sub-themes-make_default sub-translations-make_default sub-demos-make_default sub-tests-make_default FORCE
make_first: sub-src-make_first sub-themes-make_first sub-translations-make_first sub-demos-make_first sub-tests-make_first FORCE
all: sub-src-all sub-themes-all sub-translations-all sub-demos-all sub-tests-all FORCE
clean: sub-src-clean sub-themes-clean sub-translations-clean sub-demos-clean sub-tests-clean FORCE
	-$(DEL_FILE) configure-stamp
	-$(DEL_FILE) build-stamp
	-$(DEL_FILE) localconfig.pri
distclean: sub-src-distclean sub-themes-distclean sub-translations-distclean sub-demos-distclean sub-tests-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-install_subtargets sub-themes-install_subtargets sub-translations-install_subtargets sub-demos-install_subtargets sub-tests-install_subtargets FORCE
uninstall_subtargets: sub-src-uninstall_subtargets sub-themes-uninstall_subtargets sub-translations-uninstall_subtargets sub-demos-uninstall_subtargets sub-tests-uninstall_subtargets FORCE

sub-src-check: src/$(MAKEFILE)
	cd src/ && $(MAKE) -f $(MAKEFILE) check
sub-themes-check: themes/$(MAKEFILE)
	cd themes/ && $(MAKE) -f $(MAKEFILE) check
sub-translations-check: translations/$(MAKEFILE)
	cd translations/ && $(MAKE) -f $(MAKEFILE) check
sub-demos-check: demos/$(MAKEFILE)
	cd demos/ && $(MAKE) -f $(MAKEFILE) check
sub-tests-check: tests/$(MAKEFILE)
	cd tests/ && $(MAKE) -f $(MAKEFILE) check
check: sub-src-check sub-themes-check sub-translations-check sub-demos-check sub-tests-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

